runtime:
  cache_dir: ./.cache/antora

site:
  title: Tekton Tutorial
  url: https://redhat-scholars.github.io/tekton-tutorial
  start_page: tekton-tutorial::index.adoc
content:
  sources:
    - url: git@github.com:redhat-scholars/tekton-tutorial.git
      tags: []
      branches: release/0.11.x
      start_path: documentation
asciidoc:
  attributes:
    tutorial-namespace: tektontutorial
    kubernetes-version: v1.18.2
    release-version: master
    page-pagination: true
    # TODO: #24 Update the versions before release
    tekton-version: v0.11.3
    triggers-version: v0.4.0
    kn-version: v0.16.0
    tekton-cli-version: 0.11.0
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.1.9/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
