name: Tekton Tutorial Staging

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  SITE_DIR: 'gh-pages'
  STAGING_REPO: 'redhat-developer-demos/tekton-tutorial-staging'
  STAGING_SITE_PLAYBOOK: 'staging.yml'
jobs:
  build_site:
    name: Build site with Antora
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Site
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: "${{ env.STAGING_SITE_PLAYBOOK }}"
      - name: Save Generated Site
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
  deploy_site:
    runs-on: ubuntu-latest
    needs: [build_site]
    name: Deploy to Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "${{ env.STAGING_REPO }}"
          path: tekton-tutorial-staging
      - name: Download generated site
        uses: actions/download-artifact@v2
        with:
          name: site
          path: "${{ github.workspace }}/tekton-tutorial-staging/${{ env.SITE_DIR }}"
      - name: Deploy Site
        id: deploy_site
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: "${{ secrets.TKN_STAGING_SITE_DEPLOY }}"
          path: "${{ github.workspace }}/tekton-tutorial-staging/${{ env.SITE_DIR }}"
          external_repository: redhat-developer-demos/tekton-tutorial-staging
          full_commit_message: ${{ github.event.head_commit.message }}
     